theme = "base16_transparent"

[editor]
auto-info = false
true-color = true
auto-format = true
path-completion = true
auto-completion = false
gutters = ["line-numbers", "spacer"]
continue-comments = true
line-number = "absolute"
bufferline = "multiple"
scroll-lines = 2
scrolloff = 10
mouse = true

[editor.cursor-shape]
select = "block"
normal = "bar"
insert = "bar"

[editor.indent-guides]
character = "‚ñè"
render = true

[editor.smart-tab]
enable = false

[editor.lsp]
enable = false
